#%RAML 1.0 DataType
type: object
properties:
  Name:
    type: string
    minLength: 02
    maxLength: 40
    example: "Devendar reddy"
  City:
    type: string
    minLength: 03
    maxLength: 30
    example: "chennai"
  Phone:
    type: string
    minLength: 10
    maxLength: 10    
    example: "8790404804"

